Check sprint

diff --git a/ci/build-all-steps.yml b/ci/build-all-steps.yml
--- a/ci/build-all-steps.yml
+++ b/ci/build-all-steps.yml
@@ -1,5 +1,7 @@
 parameters:
   os: ''
+  task_list: ''
+  push_to_feed: false
 
 steps:
 
@@ -7,229 +9,239 @@ steps:
 - checkout: self
   clean: true
 
-# Only when building on Windows:
-- ${{ if eq(parameters.os, 'Windows_NT') }}:
+# # Only when building on Windows:
+# - ${{ if eq(parameters.os, 'Windows_NT') }}:
 
-  # Start collect diagnostics
-  - powershell: ./ci/start-collect-diagnostics.ps1
-    displayName: Start collect diagnostics
-    condition: and(succeeded(), eq(variables.collect_diagnostics, 'true'))
+#   # Start collect diagnostics
+#   - powershell: ./ci/start-collect-diagnostics.ps1
+#     displayName: Start collect diagnostics
+#     condition: and(succeeded(), eq(variables.collect_diagnostics, 'true'))
 
-# Use node 10, npm 6
-- task: NodeTool@0
-  displayName: Use node 10
-  inputs:
-    versionSpec: 10.24.1
+# # Use node 10, npm 6
+# - task: NodeTool@0
+#   displayName: Use node 10
+#   inputs:
+#     versionSpec: 10.24.1
 
-# Use .NET SDK 8
-- task: UseDotNet@2
-  displayName: 'Install .NET Core SDK 8.x'
-  inputs:
-    version: 8.x
+# # Use .NET SDK 8
+# - task: UseDotNet@2
+#   displayName: 'Install .NET Core SDK 8.x'
+#   inputs:
+#     version: 8.x
 
-# npm install
-- script: npm install
-  displayName: npm install
+# # npm install
+# - script: npm install
+#   displayName: npm install
 
-# Verify min agent demands
-- script: |
-    cd ci/verifyMinAgentDemands
-    npm install
-  displayName: npm install min agent demands
+# # Verify min agent demands
+# - script: |
+#     cd ci/verifyMinAgentDemands
+#     npm install
+#   displayName: npm install min agent demands
 
-- script: node ./ci/verifyMinAgentDemands/index.js
-  displayName: Verify min agent demands
+# - script: node ./ci/verifyMinAgentDemands/index.js
+#   displayName: Verify min agent demands
+
+# set $(currentSprint) and $(currentSprintWeek) variables
+- template: set-current-sprint-variable.yml
 
 - powershell: |
-    $currentSprintData = (Invoke-WebRequest https://whatsprintis.it -Headers @{"Accept"="application/json"} | ConvertFrom-Json)
-    $currentSprint = [int]$currentSprintData.sprint
-    $currentSprintWeek = [int]$currentSprintData.week
-    echo "##vso[task.setvariable variable=currentSprint;]$currentSprint"
-    echo "##vso[task.setvariable variable=currentSprintWeek;]$currentSprintWeek"
-  displayName: Fetch current sprint
+    $cs = $(currentSprint)
+    $cw = (currentSprintWeek)
+    $cs.GetType().FullName
+    $cw.GetType().FullName
+  displayName: Check for VARS
 
-# Filter out unchanged tasks
-- script: node ./ci/filter-tasks.js
-  displayName: Filter out unchanged tasks
-  name: getTaskPattern
-  env:
-    PACKAGE_ENDPOINT: $(Package.Endpoint)
-    PACKAGE_TOKEN: $(Package.Token)
 
-- script: node ./ci/before-build-check-tasks.js
-  displayName: Check that tasks has no duplicated libs
-  condition: |
-    and(
-      succeeded(),
-      eq(variables['build.reason'], 'PullRequest'),
-      ne(variables['numTasks'], 0)
-    )
+# # Filter out unchanged tasks
+# - script: node ./ci/filter-tasks.js
+#   displayName: Filter out unchanged tasks
+#   name: getTaskPattern
+#   env:
+#     PACKAGE_ENDPOINT: $(Package.Endpoint)
+#     PACKAGE_TOKEN: $(Package.Token)
+#     TASK_LIST: ${{ parameters.task_list }}
+#     PUSH_TO_FEED: ${{ parameters.push_to_feed }}
 
-# Verify generated files across tasks are up-to-date
-- script: dotnet run --project BuildConfigGen/BuildConfigGen.csproj --all-tasks
-  displayName: Ensure BuildConfigGen outputs are consistent
+# - script: node ./ci/before-build-check-tasks.js
+#   displayName: Check that tasks has no duplicated libs
+#   condition: |
+#     and(
+#       succeeded(),
+#       eq(variables['build.reason'], 'PullRequest'),
+#       ne(variables['numTasks'], 0)
+#     )
 
-- script: node ./ci/check-downgrading.js --task "$(task_pattern_fordowngradingcheck)" --sprint $(currentSprint) --week $(currentSprintWeek)
-  displayName: Check for downgrading tasks
-  condition: |
-      and(
-        succeeded(),
-        ne(variables['numTasksForDowngradingCheck'], 0),
-        ne(variables['COURTESY_PUSH'], 'true'),
-        eq(variables['build.reason'], 'PullRequest'),
-        eq(variables['System.PullRequest.TargetBranch'], 'master')
-      )
-  env:
-    PACKAGE_TOKEN: $(Package.Token)
+# # Verify generated files across tasks are up-to-date
+# - script: dotnet run --project BuildConfigGen/BuildConfigGen.csproj --all-tasks
+#   displayName: Ensure BuildConfigGen outputs are consistent
 
-# Build BuildConfigGen
-- task: DotNetCoreCLI@2
-  displayName: Build BuildConfigGen
-  inputs:
-    command: build
-    projects: './BuildConfigGen/BuildConfigGen.csproj'
 
-# Clean
-- script: node make.js clean
-  displayName: Clean tasks
+# - script: node ./ci/check-downgrading.js --task "$(task_pattern_fordowngradingcheck)" --sprint $(currentSprint) --week $(currentSprintWeek)
+#   displayName: Check for downgrading tasks
+#   condition: |
+#       and(
+#         succeeded(),
+#         ne(variables['numTasksForDowngradingCheck'], 0),
+#         ne(variables['COURTESY_PUSH'], 'true'),
+#         eq(variables['build.reason'], 'PullRequest'),
+#         eq(variables['System.PullRequest.TargetBranch'], 'master')
+#       )
+#   env:
+#     PACKAGE_TOKEN: $(Package.Token)
 
-# Build Tasks
-- script: node make.js serverBuild --task "$(getTaskPattern.task_pattern)"
-  displayName: Build Tasks
-  condition: and(succeeded(), ne(variables['numTasks'], 0))
+# # Build BuildConfigGen
+# - task: DotNetCoreCLI@2
+#   displayName: Build BuildConfigGen
+#   inputs:
+#     command: build
+#     projects: './BuildConfigGen/BuildConfigGen.csproj'
 
-- script: node ./ci/after-build-check-tasks.js
-  displayName: Check that tasks has no duplicated libs
-  condition: |
-    and(
-      succeeded(),
-      eq(variables['build.reason'], 'PullRequest'),
-      ne(variables['numTasks'], 0)
-    )
+# # Clean
+# - script: node make.js clean
+#   displayName: Clean tasks
 
-# Check diff for task sources
-- script: node ./ci/verify-source-changes.js "$(getTaskPattern.task_pattern)"
-  displayName: Verify task source changes
-  condition: |
-    and(
-      succeeded(),
-      ne(variables['Build.SourceBranch'], 'refs/heads/master'),
-      ne(variables['COURTESY_PUSH'], 'true'),
-      ne(variables['numTasks'], 0)
-    )
+# # Build Tasks
+# - script: node make.js serverBuild --task "$(getTaskPattern.task_pattern)"
+#   displayName: Build Tasks
+#   condition: and(succeeded(), ne(variables['numTasks'], 0))
 
-# Only on Windows:
-- ${{ if eq(parameters.os, 'Windows_NT') }}:
+# - script: node ./ci/after-build-check-tasks.js
+#   displayName: Check that tasks has no duplicated libs
+#   condition: |
+#     and(
+#       succeeded(),
+#       eq(variables['build.reason'], 'PullRequest'),
+#       ne(variables['numTasks'], 0)
+#     )
 
-  # Stage tasks individually into the package directory
-  - script: node ./ci/stage-package.js false individually
-    displayName: Stage tasks individually into the package directory
-    condition: |
-      and(
-        succeeded(),
-        ne(variables['build.reason'], 'PullRequest'),
-        ne(variables['numTasks'], 0)
-      )
+# # Check diff for task sources
+# - script: node ./ci/verify-source-changes.js "$(getTaskPattern.task_pattern)"
+#   displayName: Verify task source changes
+#   condition: |
+#     and(
+#       succeeded(),
+#       ne(variables['Build.SourceBranch'], 'refs/heads/master'),
+#       ne(variables['COURTESY_PUSH'], 'true'),
+#       ne(variables['numTasks'], 0)
+#     )
 
-  # Sign all task zips as nuget packages
-  - template: sign-all-tasks.yml
-    parameters:
-      layoutRoot: $(Build.SourcesDirectory)\_package\tasks-layout
+# # Only on Windows:
+# - ${{ if eq(parameters.os, 'Windows_NT') }}:
 
-  # Stage all the tasks into a single zip for upload
-  - script: node ./ci/stage-package.js false
-    displayName: Stage all the tasks into a single zip for upload
-    condition: |
-      and(
-        succeeded(),
-        ne(variables['build.reason'], 'PullRequest'),
-        ne(variables['numTasks'], 0)
-      )
+#   # Stage tasks individually into the package directory
+#   - script: node ./ci/stage-package.js false individually
+#     displayName: Stage tasks individually into the package directory
+#     condition: |
+#       and(
+#         succeeded(),
+#         ne(variables['build.reason'], 'PullRequest'),
+#         ne(variables['numTasks'], 0)
+#       )
 
-  # Publish artifact
-  - task: PublishBuildArtifacts@1
-    displayName: Publish package artifact
-    condition: |
-      and(
-        succeeded(),
-        ne(variables['build.reason'], 'PullRequest'),
-        ne(variables['numTasks'], 0)
-      )
-    inputs:
-      pathToPublish: _package/tasks.zip
-      artifactName: package
-      publishLocation: container
+#   # Sign all task zips as nuget packages
+#   - template: sign-all-tasks.yml
+#     parameters:
+#       layoutRoot: $(Build.SourcesDirectory)\_package\tasks-layout
 
-# Test
-- script: node make.js test
-  displayName: Run tests
-  condition: and(succeeded(), ne(variables['numTasks'], 0))
-- script: node make.js testLegacy --task "$(getTaskPattern.task_pattern)"
-  displayName: Legacy tests with node 6
-  condition: and(succeeded(), ne(variables['numTasks'], 0))
+#   # Stage all the tasks into a single zip for upload
+#   - script: node ./ci/stage-package.js false
+#     displayName: Stage all the tasks into a single zip for upload
+#     condition: |
+#       and(
+#         succeeded(),
+#         ne(variables['build.reason'], 'PullRequest'),
+#         ne(variables['numTasks'], 0)
+#       )
 
-# Publish code coverage result
-- task: PublishCodeCoverageResults@1
-  displayName: Publish Code Coverage Results
-  inputs:
-    codeCoverageTool: Cobertura
-    summaryFileLocation: $(System.DefaultWorkingDirectory)/_build/coverage/*coverage.xml
+#   # Publish artifact
+#   - task: PublishBuildArtifacts@1
+#     displayName: Publish package artifact
+#     condition: |
+#       and(
+#         succeeded(),
+#         ne(variables['build.reason'], 'PullRequest'),
+#         ne(variables['numTasks'], 0)
+#       )
+#     inputs:
+#       pathToPublish: _package/tasks.zip
+#       artifactName: package
+#       publishLocation: container
 
-# Only when building on Windows:
-- ${{ if eq(parameters.os, 'Windows_NT') }}:
+# # Test
+# - script: node make.js test
+#   displayName: Run tests
+#   condition: and(succeeded(), ne(variables['numTasks'], 0))
+# - script: node make.js testLegacy --task "$(getTaskPattern.task_pattern)"
+#   displayName: Legacy tests with node 6
+#   condition: and(succeeded(), ne(variables['numTasks'], 0))
 
-  # Stop collect diagnostics
-  - powershell: ./ci/stop-collect-diagnostics.ps1
-    displayName: Stop collect diagnostics
-    condition: |
-      and(
-        always(),
-        eq(variables.collect_diagnostics, 'true'),
-        ne(variables['numTasks'], 0)
-      )
+# # Publish code coverage result
+# - task: PublishCodeCoverageResults@1
+#   displayName: Publish Code Coverage Results
+#   inputs:
+#     codeCoverageTool: Cobertura
+#     summaryFileLocation: $(System.DefaultWorkingDirectory)/_build/coverage/*coverage.xml
 
-  - powershell: |
-      # Build the release branch name
-      $releaseBranch = "releases/m" + $(currentSprint) + "." + $(currentDate)
+# # Only when building on Windows:
+# - ${{ if eq(parameters.os, 'Windows_NT') }}:
 
-      # add config entry to avoid errors while pulling
-      git config --global user.email "$(username)@microsoft.com"
-      git config --global user.name "$(username)"
+#   # Stop collect diagnostics
+#   - powershell: ./ci/stop-collect-diagnostics.ps1
+#     displayName: Stop collect diagnostics
+#     condition: |
+#       and(
+#         always(),
+#         eq(variables.collect_diagnostics, 'true'),
+#         ne(variables['numTasks'], 0)
+#       )
 
-      # Pull commits from remote and push branch to git
-      git checkout -b $releaseBranch
-      Write-Host 'Trying to pull the remote branch..'
-      git pull https://$(GitHubPAT)@github.com/microsoft/azure-pipelines-tasks $releaseBranch
-      if (-not $?) {
-        Write-Host 'Failed to pull the remote branch. This is expected if the remote branch doesn't exist.
-      }
-      Write-Host 'Trying to push to the remote branch..'
-      git push https://$(GitHubPAT)@github.com/microsoft/azure-pipelines-tasks $releaseBranch
-    condition: |
-      and(
-        succeeded(),
-        in(variables['build.reason'], 'Schedule', 'Manual'),
-        eq(variables['COURTESY_PUSH'], 'true'),
-        eq(variables['Build.SourceBranch'], 'refs/heads/master')
-      )
-    displayName: Push release branch
+#   # set branchName
+#   - template: generate-branch-name.yml
+#     parameters:
+#       currentSprint: $(currentSprint)
+#       ${{ if eq(parameters.push_to_feed, 'true') }}:
+#         postfix: "-hotfix-$(Build.BuildId)"
 
-  - powershell: |
-      # Build the release branch name
-      $releaseBranch = "releases/m" + $(currentSprint) + "." + $(currentDate)
+#   - powershell: |
+#       $releaseBranch = $(branchName)
 
-      if ($(currentSprintWeek) -eq 3) {
-        cd $(System.DefaultWorkingDirectory)/ci/ci-release-notes
-        npm install
-        node release-notes.js --token $(GitHubPAT) --version $(currentSprint) --releaseBranch $releaseBranch
-      } else {
-        echo "Skipping since release notes generating on week 3"
-      }
-    condition: |
-      and(
-        succeeded(),
-        in(variables['build.reason'], 'Schedule', 'Manual'),
-        eq(variables['COURTESY_PUSH'], 'true'),
-        eq(variables['Build.SourceBranch'], 'refs/heads/master')
-      )
-    displayName: Create Release
+#       # add config entry to avoid errors while pulling
+#       git config --global user.email "$(username)@microsoft.com"
+#       git config --global user.name "$(username)"
+
+#       # Pull commits from remote and push branch to git
+#       git checkout -b $releaseBranch
+#       Write-Host 'Trying to pull the remote branch..'
+#       git pull https://$(GitHubPAT)@github.com/microsoft/azure-pipelines-tasks $releaseBranch
+#       if (-not $?) {
+#         Write-Host 'Failed to pull the remote branch. This is expected if the remote branch doesn't exist.
+#       }
+#       Write-Host 'Trying to push to the remote branch..'
+#       git push https://$(GitHubPAT)@github.com/microsoft/azure-pipelines-tasks $releaseBranch
+#     condition: |
+#       and(
+#         succeeded(),
+#         in(variables['build.reason'], 'Schedule', 'Manual'),
+#         eq(variables['COURTESY_PUSH'], 'true'),
+#         eq(variables['Build.SourceBranch'], 'refs/heads/master')
+#       )
+#     displayName: Push release branch
+
+#   - powershell: |
+#       $releaseBranch = $(branchName)
+#       if ($(currentSprintWeek) -eq 3) {
+#         cd $(System.DefaultWorkingDirectory)/ci/ci-release-notes
+#         npm install
+#         node release-notes.js --token $(GitHubPAT) --version $(currentSprint) --releaseBranch $releaseBranch
+#       } else {
+#         echo "Skipping since release notes generating on week 3"
+#       }
+#     condition: |
+#       and(
+#         succeeded(),
+#         in(variables['build.reason'], 'Schedule', 'Manual'),
+#         eq(variables['COURTESY_PUSH'], 'true'),
+#         eq(variables['Build.SourceBranch'], 'refs/heads/master')
+#       )
+#     displayName: Create Release
